goal_setter/config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                 users GET    /users(.:format)                                                                         users#index
#                                       POST   /users(.:format)                                                                         users#create
#                              new_user GET    /users/new(.:format)                                                                     users#new
#                                  user GET    /users/:id(.:format)                                                                     users#show
#                           new_session GET    /session/new(.:format)                                                                   sessions#new
#                               session DELETE /session(.:format)                                                                       sessions#destroy
#                                       POST   /session(.:format)                                                                       sessions#create
#                                 goals GET    /goals(.:format)                                                                         goals#index
#                                       POST   /goals(.:format)                                                                         goals#create
#                              new_goal GET    /goals/new(.:format)                                                                     goals#new
#                             edit_goal GET    /goals/:id/edit(.:format)                                                                goals#edit
#                                  goal GET    /goals/:id(.:format)                                                                     goals#show
#                                       PATCH  /goals/:id(.:format)                                                                     goals#update
#                                       PUT    /goals/:id(.:format)                                                                     goals#update
#                                       DELETE /goals/:id(.:format)                                                                     goals#destroy
#                                  root GET    /                                                                                        users#index
#                              comments POST   /comments(.:format)                                                                      comments#create
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :goals

  root to: 'users#index'

  resources :comments, only: [:create]
end

goal_setter/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :bigint           not null, primary key
#  completed  :boolean          default(FALSE), not null
#  details    :text
#  private    :boolean          default(FALSE), not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  owner_id   :integer          not null
#
# Indexes
#
#  index_goals_on_owner_id  (owner_id)
#

class Goal < ApplicationRecord
	validates :owner, :title, presence: true
	validates :title, length: { minimum: 6 }

	belongs_to :owner,
	class_name: :User

	has_many :comments,
	as: :commentable,
	dependent: :destroy
end

goal_setter/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	before_action :ensure_logged_in

	def index
		@goals = current_user.goals
		render :index
	end

	def show
		@goal = Goal.find_by(id: params[:id])
		if @goal
			render :show
		else
			flash.now[:errors] = 'Not found!'
			render 'layouts/not_found', status: :not_found
		end
	end

	def new
		@goal = Goal.new
		render :new
	end

	def edit
		@goal = current_user.goals.find_by(id: params[:id])
		if @goal
			render :edit
		else
			flash.now[:errors] = 'Not found!'
			render 'layouts/not_found', status: :not_found
		end
	end

	def create
		@goal = Goal.new(goal_params)
		@goal.owner_id = current_user.id
		if @goal.save
			redirect_to goal_url(@goal)
		else
			flash.now[:errors] = @goal.errors.full_messages
			render :new
		end
	end

	def update
		@goal = current_user.goals.find_by(id: params[:id])
		if @goal
			if @goal.update_attributes(goal_params)
				redirect_to goals_url
			else
				flash.now[:errors] = @goal.errors.full_messages
				render :edit
			end
		else
			flash.now[:errors] = 'Not found!'
			render 'layouts/not_found', status: :not_found
		end
	end

	def destroy
		@goal = current_user.goals.find_by(id: params[:id])
		if @goal
			@goal.destroy
			redirect_to goals_url
		else
			flash.now[:errors] = 'Not found!'
			render 'layouts/not_found', status: :not_found
		end
	end

	private

	def goal_params
		params.require(:goal).permit(:title, :details, :private, :completed)
	end
end

goal_setter/app/helpers/goals_helper.rb
module GoalsHelper
end

goal_setter/app/views/goals/_complete_button.html.erb
<% if goal.completed %>
	<form action="<%=goal_url(goal)%>" method="post">
		<%= auth_token %>
		<input type="hidden" name="_method" value="patch">
		<input type="hidden" name="goal[completed]" value="false">
		<button type="submit">Oops! Did not complete.</button>
	</form>
<% else %>
	<form action="<%=goal_url(goal)%>" method="post">
		<%= auth_token %>
		<input type="hidden" name="_method" value="patch">
		<input type="hidden" name="goal[completed]" value="true">
		<button type="submit">Complete</button>
	</form>
<% end %>

goal_setter/app/views/goals/_form.html.erb
<% action = (submit == 'New Goal' ? goals_url : goal_url(goal)) %>

<form action="<%=action%>" method="post">
	<%= auth_token %>
	<% unless submit == 'New Goal' %>
		<input type="hidden" name="_method" value="patch">
	<% end %>

	<label for="title">Title: </label>
	<input type="text" name="goal[title]" id="title" value="<%=goal.title%>">

	<label for="details">Details: </label>
	<textarea name="goal[details]" id="details" cols="30" rows="10"
	><%= goal.details %></textarea>

	<label for="private">Private? </label>
	<input type="checkbox" name="goal[private]" id="private" value="true"
	<%= goal.private == true ? 'checked' : '' %>>

	<label for="completed">Completed? </label>
	<input type="checkbox" name="goal[completed]" id="completed" value="true"
	<%= goal.completed == true ? 'checked' : '' %>>

	<button type="submit"><%= submit %></button>
</form>

goal_setter/app/views/goals/_goals.html.erb
<% goals.each do |goal| %>
	<% next if (!current_user || goal.owner_id != current_user.id) && goal.private %>
	<ul><li><%= link_to goal.title, goal_url(goal) %></li></ul>
	<p><%= goal.private ? 'Private' : 'Public'  %></p>
	<p><%= goal.completed ? 'Complete' : 'Ongoing' %></p>
	<%= render 'goals/complete_button', goal: goal %>
	<form action="<%=goal_url(goal)%>" method="post">
		<%= auth_token %>
		<input type="hidden" name="_method" value="delete">
		<button type="submit"><%= "delete '#{goal.title}' goal" %></button>
	</form>
<% end %>

goal_setter/app/views/goals/edit.html.erb
<%= render 'form', goal: @goal, submit: 'Edit Goal' %>

goal_setter/app/views/goals/index.html.erb
<%= render 'goals', goals: @goals %>

goal_setter/app/views/goals/new.html.erb
<%= render 'form', goal: @goal, submit: 'New Goal' %>

goal_setter/app/views/goals/show.html.erb
<table>
	<tbody>
		<tr>
			<th>Title: </th>
			<td><%= @goal.title %></td>
		</tr>
		<tr>
			<th>Details: </th>
			<td><%= @goal.details %></td>
		</tr>
		<tr>
			<th>Visibility: </th>
			<td><%= @goal.private == true ? 'Private' : 'Public' %></td>
		</tr>
		<tr>
			<th>Finished?: </th>
			<td><%= @goal.completed == true ? 'Completed' : 'Ongoing' %></td>
		</tr>
		<% if @goal.owner == current_user %>
			<tr>
				<th>Completed?</th>
				<td><%= render 'complete_button', goal: @goal %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h2>Comments</h2>
<% @goal.comments.each do |comment| %>
	<p><%= comment.body %></p>
<% end %>

<h2>New Comment</h2>
<form action="<%=comments_url%>" method="post">
	<%= auth_token %>
	<label for="body">Comment</label>
	<input type="hidden" name="comment[commentable_id]" value="<%=@goal.id%>">
	<input type="hidden" name="comment[commentable_type]" value="Goal">
	<textarea name="comment[body]" id="body" cols="30" rows="10"></textarea>
	<button type="submit">Save Comment</button>
</form>